### ISSUE TITLE
5.0+ should be built from source

### ISSUE THREAD

**Issue by spalger** [elastic/libesvm#30]
Starting with elasticsearch 5.0 we should stop relying on snapshot downloads and instead build elasticsearch from source. This should be simple enough to do, and by bundling the [gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) the user experience won't be much different at all.

**Pros:**
- install any git reference from the elasticsearch repo
- no rebuild/redownload necessary when branches haven't updated
- no partial install issues

**Cons:**
- Possible errors are expanded (build errors in master break esvm)
- Have to maintain snapshots for pre 5.0

**Comment by Bargs** [comment]
Pro: In development core plugins will also get built from source and can be installed via esvm
