### ISSUE TITLE
site down: https://esvm-props.kibana.rocks/builds ?

### ISSUE THREAD

**Issue by blacktop** [elastic/libesvm#43]
I can't test kibana plugins and I think this line is the reason: https://github.com/elastic/libesvm/blob/master/lib/fetchAllTags.js#L19

I think the site is down?

**Comment by spalger** [comment]
Fixed, thanks @blacktop

**Comment by mjrk** [comment]
Thanks for the fast fix last time!

Seems to be down again (or another error) because fetchAllTags() in resolveVersion() does return an empty list.

**Comment by spalger** [comment]
@mjrk yeah, it did go down for a while but it should be back up

**Comment by mjrk** [comment]
@spalger wouldn't it be easier to raise an exception in fetchAllTags() when the site is down? I had to step through the code to find out the source of the problem.

**Comment by szydan** [comment]
Seems down again
https://esvm-props.kibana.rocks/builds

**Comment by spalger** [comment]
thanks @szydan, should be able to fix once I get through airport security

**Comment by blacktop** [comment]
It seems like it goes down a lot, would it be easier to somehow, parse the repos in Github (not that Github doesn't also go down sometimes) 😉

**Comment by yujin-emma** [comment]
I recently see the server down again, any one can help to check this issue?

Thanks
Emma
