### ISSUE TITLE
Fatal error: Unable to find a version for "*"

### ISSUE THREAD

**Issue by nikhil-ahir-dox** [elastic/libesvm#47]
Hi team, i am trying to run a Kibana instance on my Windows10 machine. As per my findings the Kibana project is using grunt-esvm to load a elasticsearch cluster. And grunt-esvm internally uses libesvm. Now my issue is, when i try running the esvm cluster with following configuration it is giving me error:

Configuration:-
![image](https://user-images.githubusercontent.com/29054681/27116229-a9aecdee-50ed-11e7-9bf1-ede1b8b95473.png)

Error Message:-
![image](https://user-images.githubusercontent.com/29054681/27116268-e0f5d720-50ed-11e7-8be3-51b98234d550.png)

I even tried with the branch option and am receiving the below error:
![image](https://user-images.githubusercontent.com/29054681/27116316-2d6b1908-50ee-11e7-870d-daee159566ca.png)

I am using "grunt-esvm": "3.2.6" which installs "libesvm": "3.7.0".

I want to load the the 5.4 branch of elasticsearch cluster. Would appreciate any help :)

**Comment by spalger** [comment]
The option should definitely be `branch: '5.4'`. Can you run the following from the root of the Kibana source directory and include the entire output of the command in a [gist](https://gist.github.com/]?

```sh
./node_modules/.bin/grunt esvm:dev:keepalive --stack --debug --verbose
```

**Comment by nikhil-ahir-amdocs** [comment]
Thanks spalger for the reply. I tried the above command and it also failed. Please find the output for the above command below:-

`$ ./node_modules/.bin/grunt esvm:dev:keepalive --stack --debug --verbose
Initializing
Command-line options: --stack, --debug=1, --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Reading .node-version...OK
Initializing config...OK

Registering "grunt-angular-translate" local Npm module tasks.
Reading C:\projects\kibana\node_modules\grunt-angular-translate\package.json...OK
Parsing C:\projects\kibana\node_modules\grunt-angular-translate\package.json...OK
Loading "angular-translate.js" tasks...OK
+ i18nextract

Registering "grunt-aws-s3" local Npm module tasks.
Reading C:\projects\kibana\node_modules\grunt-aws-s3\package.json...OK
Parsing C:\projects\kibana\node_modules\grunt-aws-s3\package.json...OK
Loading "aws_s3.js" tasks...OK
+ aws_s3

Registering "grunt-babel" local Npm module tasks.
Reading C:\projects\kibana\node_modules\grunt-babel\package.json...OK
Parsing C:\projects\kibana\node_modules\grunt-babel\package.json...OK
Loading "babel.js" tasks...OK
+ babel

Registering "grunt-contrib-clean" local Npm module tasks.
Reading C:\projects\kibana\node_modules\grunt-contrib-clean\package.json...OK
Parsing C:\projects\kibana\node_modules\grunt-contrib-clean\package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-copy" local Npm module tasks.
Reading C:\projects\kibana\node_modules\grunt-contrib-copy\package.json...OK
Parsing C:\projects\kibana\node_modules\grunt-contrib-copy\package.json...OK
Loading "copy.js" tasks...OK
+ copy

Registering "grunt-esvm" local Npm module tasks.
Reading C:\projects\kibana\node_modules\grunt-esvm\package.json...OK
Parsing C:\projects\kibana\node_modules\grunt-esvm\package.json...OK
Loading "esvm.js" tasks...OK
+ esvm, esvm_shutdown

Registering "grunt-karma" local Npm module tasks.
Reading C:\projects\kibana\node_modules\grunt-karma\package.json...OK
Parsing C:\projects\kibana\node_modules\grunt-karma\package.json...OK
Loading "grunt-karma.js" tasks...OK
+ karma

function bold() { [native code] }
Reading C:\projects\kibana\node_modules\grunt-run\package.json...OK
Parsing C:\projects\kibana\node_modules\grunt-run\package.json...OK
Loading "run.js" tasks...OK
+ run, stop, wait

function bold() { [native code] }
Reading C:\projects\kibana\node_modules\grunt-simple-mocha\package.json...OK
Parsing C:\projects\kibana\node_modules\grunt-simple-mocha\package.json...OK
Loading "simple-mocha.js" tasks...OK
+ simplemocha

function bold() { [native code] }
Loading "check_added_filenames.js" tasks...OK
+ checkAddedFilenames
Loading "check_plugins.js" tasks...OK
+ checkPlugins
Loading "collect_files_to_commit.js" tasks...OK
+ collectFilesToCommit
Loading "eslint.js" tasks...OK
+ eslint
Loading "functional_test_runner.js" tasks...OK
+ functional_test_runner
Loading "jenkins.js" tasks...OK
+ jenkins, jenkins:env, jenkins:selenium, jenkins:unit
Loading "licenses.js" tasks...OK
+ licenses
Loading "lint_staged_files.js" tasks...OK
+ lintStagedFiles
Loading "plugin.js" tasks...OK
+ plugin
Loading "precommit.js" tasks...OK
+ precommit
Loading "reject_rej_files.js" tasks...OK
+ rejectRejFiles
Loading "release_packages.js" tasks...OK
+ _publishPackages:confirm, _publishPackages:upload, publishPackages:production, publishPackages:staging
Loading "release.js" tasks...OK
+ _release:complete, _release:confirmUpload, _release:loadS3Config, release
Loading "setup_kibana.js" tasks...OK
+ setup_kibana
Loading "sterilize.js" tasks...OK
+ sterilize
Loading "test_jest.js" tasks...OK
+ test:jest
Loading "test.js" tasks...OK
+ quick-test, test, test:api, test:api:runner, test:api:server, test:browser, test:browser-ci, test:coverage, test:dev, test:quick, test:server, test:ui, test:ui:server, test:uiRelease, test:visualRegression:buildGallery
Loading "ui_framework.js" tasks...OK
+ uiFramework:build, uiFramework:start

function bold() { [native code] }
Loading "archives.js" tasks...OK
+ _build:archives
Loading "babel_cache.js" tasks...OK
+ _build:babelCache
Loading "babel_options.js" tasks...OK
+ _build:babelOptions
Loading "data.js" tasks...OK
+ _build:data
Loading "download_node_builds.js" tasks...OK
+ _build:downloadNodeBuilds, _build:extractNodeBuilds
Loading "index.js" tasks...OK
+ build
Loading "install_npm_deps.js" tasks...OK
+ _build:installNpmDeps
Loading "installed_plugins.js" tasks...OK
+ _build:plugins
Loading "notice.js" tasks...OK
+ _build:notice
Loading "os_packages.js" tasks...OK
+ _build:osPackages
Loading "os_shell_scripts.js" tasks...OK
+ _build:osShellScripts
Loading "package_json.js" tasks...OK
+ _build:packageJson
Loading "pleaserun.js" tasks...OK
+ _build:pleaseRun
Loading "readme.js" tasks...OK
+ _build:readme
Loading "remove_pkg_json_deps.js" tasks...OK
+ _build:removePkgJsonDeps
Loading "shasums.js" tasks...OK
+ _build:shasums
Loading "verify_translations.js" tasks...OK
+ _build:check, _build:verifyTranslations
Loading "versioned_links.js" tasks...OK
+ _build:versionedLinks
Loading "Gruntfile.js" tasks...OK
>> No tasks were registered or unregistered.

Running tasks: esvm:dev:keepalive

Running "esvm:dev:keepalive" (esvm) task
[D] Task source: C:\projects\kibana\node_modules\grunt-esvm\tasks\esvm.js
Verifying property esvm.dev exists in config...OK
File: [no files]
Options: quiet=false, fresh, purge=false, shield=undefined, branch="master", config={"path":{"data":"C:\\projects\\kibana\\esvm\\data_dir"},"cluster":{"name":"esvm-dev"}}, directory="C:\\projects\\kibana\\esvm\\dev"
[D] Creating libesvm cluster with: {
  "fresh": true,
  "purge": false,
  "branch": "master",
  "config": {
    "path": {
      "data": "C:\\projects\\kibana\\esvm\\data_dir"
    },
    "cluster": {
      "name": "esvm-dev"
    },
    "http": {
      "port": 9200
    }
  },
  "directory": "C:\\projects\\kibana\\esvm\\dev"
}
starting up "dev" cluster
Keeping elasticsearch alive, to shutdown press command/control+c
Fatal error: Cannot read property 'master' of undefined
TypeError: Cannot read property 'master' of undefined
    at C:\projects\kibana\node_modules\libesvm\lib\installFromBranch.js:19:23
    at tryCatcher (C:\projects\kibana\node_modules\libesvm\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\projects\kibana\node_modules\libesvm\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\projects\kibana\node_modules\libesvm\node_modules\bluebird\js\main\promise.js:581:18)
    at Async._drainQueue (C:\projects\kibana\node_modules\libesvm\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\projects\kibana\node_modules\libesvm\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\projects\kibana\node_modules\libesvm\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
`
Anything that you can get from this?

**Comment by spalger** [comment]
@nikhil-ahir-dox your cache is probably corrupt, mind clearing it out?

It's stored at `{os.tmpdir()}/libesvm.cache.{version}.json`, I'm not sure what the tmpdir for windows is, but you can find it out by running:

```sh
node -e "console.log(require('os').tmpdir())"
```

**Comment by nikhil-ahir-dox** [comment]
Hey thanks @spalger for you support 👍  Actually it was an proxy issue. My bad :) Closing the thread as there was not issue.
