### ISSUE TITLE
site down: https://esvm-props.kibana.rocks/builds

### ISSUE THREAD

**Issue by yujin-emma** [elastic/libesvm#58]
I want to install a es server but have this issue: TypeError: Cannot read property '6.0' of undefined
I think the reason is the fetchAllTags return nothing, and the site to get it is down

Can somebody help check and recover it?

Thanks

**Comment by spalger** [comment]
Hey @yujin-emma, I'm surprised to hear that anyone was still relying on this tool. We've shutdown the online service and libesvm is going to be archived. I've included some options in the warning at the top of the readme, but I highly recommend using a more modern option for starting ES.
